/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-bright': '#3a3939',
        outline: '#99907e',
        'on-tertiary-container': '#2e3b77',
        'tertiary-container': '#9ba8eb',
        'on-surface': '#e5e2e1',
        'surface-container-highest': '#353534',
        'on-tertiary': '#1e2b66',
        'outline-variant': '#4d4637',
        'on-primary-container': '#503d00',
        'inverse-surface': '#e5e2e1',
        'surface-container-high': '#2a2a2a',
        'on-secondary-container': '#b9b5ad',
        'secondary-fixed-dim': '#cac6be',
        'surface-container-low': '#1c1b1b',
        tertiary: '#b9c4ff',
        background: '#131313',
        error: '#ffb4ab',
        'on-background': '#e5e2e1',
        'on-secondary': '#32302b',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed': '#1d1c17',
        'secondary-fixed': '#e7e2da',
        'tertiary-fixed': '#dde1ff',
        'surface-variant': '#353534',
        'on-surface-variant': '#d0c5b2',
        'primary-fixed-dim': '#e6c364',
        'inverse-on-surface': '#313030',
        'on-tertiary-fixed-variant': '#35437e',
        'secondary-container': '#494741',
        primary: '#e6c364',
        'surface-dim': '#131313',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#584400',
        secondary: '#cac6be',
        'inverse-primary': '#755b00',
        'on-primary': '#3d2e00',
        'surface-tint': '#e6c364',
        'surface-container': '#201f1f',
        'primary-container': '#c9a84c',
        'surface-container-lowest': '#0e0e0e',
        'on-error': '#690005',
        'primary-fixed': '#ffe08f',
        'error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '80px',
        gutter: '32px',
        'section-gap': '160px',
        unit: '8px',
        'margin-mobile': '24px',
      },
      fontFamily: {
        'body-md': ['DM Sans', 'sans-serif'],
        'display-lg': ['EB Garamond', 'serif'],
        technical: ['JetBrains Mono', 'monospace'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'headline-lg-mobile': ['EB Garamond', 'serif'],
        'display-lg-mobile': ['EB Garamond', 'serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'label-caps': ['DM Sans', 'sans-serif'],
        'headline-lg': ['EB Garamond', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['80px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        technical: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'display-lg-mobile': ['48px', { lineHeight: '1.1', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
      },
      keyframes: {
        shimmer: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        pulse: {
          '0%': { boxShadow: '0 0 0 0 rgba(74,222,128,0.7)' },
          '70%': { boxShadow: '0 0 0 10px rgba(74,222,128,0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(74,222,128,0)' },
        },
        blink: { 'from, to': { opacity: '1' }, '50%': { opacity: '0' } },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        bounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        shimmer: 'shimmer 3s infinite linear',
        'dot-pulse': 'pulse 2s infinite',
        blink: 'blink 1s step-end infinite',
        fadeIn: 'fadeIn 0.5s ease',
        bounce: 'bounce 2s infinite',
      },
    },
  },
  plugins: [],
}
